### ISSUE TITLE
GPU Miner

### ISSUE THREAD

**Issue by PsychoSterope** [jceminer/cn_gpu_miner#1]
Do I add the config to the cpu miner or is there nothing for the combo miner yet?

**Comment by jceminer** [comment]
The combo is not released yet, now in test phase.
i opened that GitHub repo to give some doc in advance.
the combo will be for Win64 only

**Comment by PsychoSterope** [comment]
I wait in anticipation! I love the cpu miner!

**Comment by jceminer** [comment]
It's available now, but as an early prototype. No autoconfig, one algo for all the CPU and GPU. It will be fixed in later versions.
