### ISSUE TITLE
Error in my vega 64

### ISSUE THREAD

**Issue by samvicky26** [jceminer/cn_gpu_miner#13]
Starting GPU Mining thread 22, on GPU 3
Created OpenCL Context for GPU 3 at 00000195b06b7950
Created OpenCL Thread 22 Command-Queue for GPU 3 at 00000195b04fea40
Scratchpad Allocation success for OpenCL Thread 22
Allocating big 2400MB scratchpad for OpenCL Thread 22...
Compiling kernels of OpenCL Thread 22...
Compilation of OpenCL kernels failed.
Error: CL_BUILD_PROGRAM_FAILURE Code: s-331.16

Starting GPU Mining thread 23, on GPU 3
Created OpenCL Thread 23 Command-Queue for GPU 3 at 00000195b04ff220
Scratchpad Allocation success for OpenCL Thread 23
Allocating big 2400MB scratchpad for OpenCL Thread 23...
Compiling kernels of OpenCL Thread 23...
Compilation of OpenCL kernels failed.
Error: CL_BUILD_PROGRAM_FAILURE Code: s-331.16

Getting this error on my vega 64. I am on 18.8.1 driver and win 10. I even tried --auto but same issue

**Comment by jceminer** [comment]
I got this bug reported on Bitcointalk too, that's the symptom of same problem as
https://github.com/jceminer/cn_gpu_miner/issues/4

i'm fixing and i release an "emergency" 0.32j (and will remove 0.32i from download).
Thanks for fast report.

**Comment by jceminer** [comment]
Fixed in 0.32j

**Comment by samvicky26** [comment]
Thanks for the fix
