### ISSUE TITLE
NO true explanation of Alpha,Beta,Gamma etc

### ISSUE THREAD

**Issue by Patrickdurbin** [jceminer/cn_gpu_miner#16]
I really don't understand what the diffrences between alpha beta delta and so on are. I see alpha 128 and 64 sometimes. Sometimes I see beta as 8 or 16 ( is this worksize) delta... (ist that memchunk?) I don't really understand.

Could you please elaborate what they do? I would like to tune my miner as much as possible.  However I don't see a good explanation just examples.

**Comment by jceminer** [comment]
Hello,

All greeks but alpha and beta are deprecated now, i still document them for backward compatibility, but they are ignored now.
What they do is about how the internal GPU parallelisation and memory accesses are made, i cannot tell more without revealing technical secrets.
On most GPU alpha=64 and beta=8 are optimal, on smaller GPU like RX550 alpha=32 may be better, and on bigger ones like Vega, trying 128 (and/or worksize=16) may give a little boost too.
