### ISSUE TITLE
033b on nicehash cnv8 isn't working

### ISSUE THREAD

**Issue by Quake4** [jceminer/cn_gpu_miner#20]
report 0 hashrate

**Comment by jceminer** [comment]
Hello,
I proof tested cnv8 on the Killallasics test pool, but not on nicehash v8. I give a try and come back.

**Comment by jceminer** [comment]
Just tested, on CPU, it works. I got a valid share, and Nicehash website reported my hashrate as non-zero (yet low).

> 11:26:49 | Connecting to mining pool cryptonightv8.eu.nicehash.com:3367 ...
11:26:49 | Connected to pool. Now logging in...
11:26:50 | Successfuly logged as xxxxxxxxxxxxx
11:26:50 | Pool changes Difficulty to 100001.
...
11:29:41 | Hashrate CPU Thread 0: 10.56 h/s
11:29:41 | Hashrate CPU Thread 1: 8.03 h/s
11:29:41 | Total: 18.58 h/s - Max: 23.05 h/s
11:30:11 | Pool sends a new Job.
11:30:27 | CPU Thread 1 finds a Share, value 100001
11:30:27 | Accepted by the pool in 293 ms.

**Comment by jceminer** [comment]
On GPU, my v8 implementation is to be considered non-usable except for test. A workable version won't be available until november.

**Comment by Quake4** [comment]
Yes, i write about gpu version. Ok. Thanks. Waiting...

**Comment by Quake4** [comment]
thanks. working 0.32b
