### ISSUE TITLE
GPU Temp and Fan speed support

### ISSUE THREAD

**Issue by gk57** [jceminer/cn_gpu_miner#3]
Hi,

GPU miner works well with Vega 64, Hashrate is consistent and no crashes. Consider adding support for GPU temperature and fan speed to the miner.

**Comment by jceminer** [comment]
Right, it's planned, but not as high priority, i'm focusing on bugfixes and perf improvment for now. But sure that's a have-to-have feature.

**Comment by jceminer** [comment]
It has been added in 0.32e
press T to get the fan/temp report. It's also in the JSON output.
