### ISSUE TITLE
rx290 setting

### ISSUE THREAD

**Issue by rb116** [jceminer/cn_gpu_miner#31]
Hi, 
I would like to try your miner and only found 7970 setting. Do you hv the recommended setting for RX290 Hawaii 4GB GPU setting ? I m currently doing 820h with srb 170.

**Comment by jceminer** [comment]
the 7970 is for Tahiti, a very different architecture.
I don't have a Hawaii 4G to test myself, my last working GCN2 card is a Bonaire (a stripped-down Hawaii core) but I asked on Bitcointalk for an optimal config from a user that quoted
> JCE CNv8 you can get 900 on with 1120/1420
So far he gave little details but i guess he has a 290 and you're talking about v8 algo.
Topic here:
https://bitcointalk.org/index.php?topic=5059717.msg48561739#msg48561739

**Comment by rb116** [comment]
My bad. Just read tht your miner doesn’t support win7.. any plan?

**Comment by jceminer** [comment]
Minimum is win8.1, no win7 support planned.
I relaxed the thread limit to 3 threads per gpu in the 0.33b14

**Comment by platinum4** [comment]
Please close if resolved (Windows 10/7 issue)
