### ISSUE TITLE
adding zbucks

### ISSUE THREAD

**Issue by wesleykad** [jceminer/cn_gpu_miner#9]
Hi @jceminer 

Could you perhaps add zBucks (https://zbucks.org) to the list on coins.bat.
Algo: cn-heavy

Thanks

**Comment by jceminer** [comment]
Hi,
sure, next planned coins are zBucks, mox and xcash

**Comment by jceminer** [comment]
zBucks is in version 0.32h

**Comment by wesleykad** [comment]
@jceminer Thank you, will let the community know
